const carData = [
  {id:"car1", name:"Porsche 911", category:"sports", label:"Sports", type:"car", price:"Iconic performance", image:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=85", description:"A legendary sports car known for its distinctive design, performance and long-running heritage.", specs:["Rear-engine layout","Performance-focused design","Iconic 911 identity"]},
  {id:"car2", name:"Mercedes-Benz S-Class", category:"luxury", label:"Luxury", type:"car", image:"https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1000&q=85", description:"A flagship luxury sedan combining premium comfort, technology and refined design.", specs:["Luxury sedan","Advanced driver assistance","Premium interior"]},
  {id:"car3", name:"Tesla Model S", category:"electric", label:"Electric", type:"car", image:"https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1000&q=85", description:"A well-known electric sedan associated with long-range EV technology and rapid acceleration.", specs:["Fully electric","Minimalist cabin","High-performance variants"]},
  {id:"car4", name:"Ford Mustang", category:"sports", label:"Sports", type:"car", image:"https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=1000&q=85", description:"An iconic American performance car with a recognizable muscle-car identity.", specs:["Performance coupe","Long-running nameplate","Classic muscle-car character"]},
  {id:"car5", name:"Range Rover", category:"luxury", label:"Luxury SUV", type:"car", image:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1000&q=85", description:"A premium SUV known for its combination of luxury, road presence and off-road capability.", specs:["Luxury SUV","All-terrain capability","Premium cabin"]},
  {id:"car6", name:"BMW i4", category:"electric", label:"Electric", type:"car", image:"https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1000&q=85", description:"An electric performance sedan combining BMW styling with battery-powered driving.", specs:["Electric sedan","Sporty handling","Modern cabin technology"]}
];

const laptopData = [
  {id:"lap1", name:"MacBook Pro", category:"creator", label:"Creator", type:"laptop", image:"https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1000&q=85", description:"A premium laptop family popular for development, creative work and professional workflows.", specs:["High-resolution display options","Powerful processor options","Premium build"]},
  {id:"lap2", name:"Dell XPS 15", category:"student", label:"Study & Work", type:"laptop", image:"https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=1000&q=85", description:"A premium Windows laptop line designed for productivity, study and demanding everyday tasks.", specs:["Windows laptop","Premium design","Strong productivity focus"]},
  {id:"lap3", name:"ASUS ROG Strix", category:"gaming", label:"Gaming", type:"laptop", image:"https://images.unsplash.com/photo-1593640495253-23196b27a87f?auto=format&fit=crop&w=1000&q=85", description:"A gaming-focused laptop family built around performance, cooling and gaming features.", specs:["Gaming-focused hardware","High refresh-rate options","Performance cooling"]},
  {id:"lap4", name:"Lenovo Legion", category:"gaming", label:"Gaming", type:"laptop", image:"https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1000&q=85", description:"A popular gaming laptop line offering powerful hardware and a practical performance-oriented design.", specs:["Gaming performance","Dedicated graphics options","High refresh-rate displays"]},
  {id:"lap5", name:"HP Spectre x360", category:"student", label:"2-in-1", type:"laptop", image:"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1000&q=85", description:"A flexible premium laptop family known for convertible designs and portability.", specs:["2-in-1 design","Touchscreen options","Portable form factor"]},
  {id:"lap6", name:"Microsoft Surface Laptop", category:"creator", label:"Everyday", type:"laptop", image:"https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=1000&q=85", description:"A clean, portable laptop line suited to everyday productivity, study and creative work.", specs:["Portable design","Windows ecosystem","Productivity focused"]}
];

const placeData = [
  {id:"place1", name:"Dubai", country:"UAE", image:"https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=85", description:"A modern destination famous for futuristic architecture, shopping, beaches and desert experiences.", things:["Visit Burj Khalifa","Explore Dubai Marina","Go on a desert safari","Visit Dubai Mall"]},
  {id:"place2", name:"Tokyo", country:"Japan", image:"https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=85", description:"A high-energy city where modern technology, food, traditional culture and entertainment meet.", things:["Explore Shibuya","Visit Senso-ji","Try local food","See Tokyo Skytree"]},
  {id:"place3", name:"Paris", country:"France", image:"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=85", description:"A classic destination known for architecture, museums, cafés and iconic landmarks.", things:["Visit Eiffel Tower","Explore Louvre area","Walk along the Seine","Try French cafés"]}
];
